Event
| where Source == "Microsoft-Windows-Sysmon"
| where EventID == 1
| where EventData has "rundll32"
| where EventData has_any (
    "javascript:",
    "vbscript:",
    "mshtml,RunHTMLApplication",
    "mshtml,#135",
    "advpack.dll,LaunchINFSection",
    "ieadvpack.dll,LaunchINFSection",
    "syssetup.dll,SetupInfObjectInstallAction"
  )
| project TimeGenerated, Computer, RenderedDescription
| sort by TimeGenerated desc
